export const CHECK_CAPTCHA = 'CHECK_CAPTCHA'

export const CHANGE_LOGING_STATUS = 'CHANGE_LOGING_STATUS'

export const GET_NEWS_LISTS = 'GET_NEWS_LISTS'

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const ADD_ARTICLE = 'ADD_ARTICLE'

export const DEL_NEWS = 'DEL_NEWS'

export const GET_ARTICLE_DETAIL = 'GET_ARTICLE_DETAIL'

export const UPDATE_ARTICLE = 'UPDATE_ARTICLE'

export const DELETE_ARTICLE = 'DELETE_ARTICLE'

export const CREATE_CATEGORIES = 'CREATE_CATEGORIES'

export const UPDATE_CATEGORIES = 'UPDATE_CATEGORIES'

export const DELETE_CATEGORIES = 'DELETE_CATEGORIES'

export const LOGIN = 'LOGIN'

export const LOGOUT = 'LOGOUT'

export const GET_APPLICATION_LIST = 'GET_APPLICATION_LIST'

export const GET_POINT_LOGS = 'GET_POINT_LOGS'

export const GET_MEMBERS_LIST = 'GET_MEMBERS_LIST'

export const SHOW_MEMBER_DETAIL = 'SHOW_MEMBER_DETAIL';

export const GET_AD_USER_LIST = 'GET_AD_USER_LIST';



export const ADMIN_LOGIN = 'ADMIN_LOGIN';

export const ADMIN_CHANGE_LOGINING = 'ADMIN_CHANGE_LOGINING';

export const GET_MENUS = 'GET_MENUS';
export const GET_NODES = 'GET_NODES';
export const ADD_NODE = 'ADD_NODE';

export const ADD_MENUS = 'ADD_MENUS';
export const REFRESH_TOKEN = 'REFRESH_TOKEN';
export const GET_HOSPITAL = 'GET_HOSPITAL';
export const GET_ITEMS = 'GET_ITEMS';
export const GET_PACKAGE = 'GET_PACKAGE';
export const GET_ALL_ITEMS = 'GET_ALL_ITEMS';
export const GET_GOOD = 'GET_GOOD';
export const GET_USER = 'GET_USER';
export const ADMIN_LOGOUT = 'ADMIN_LOGOUT';
export const GET_APPOINTMENT = 'GET_APPOINTMENT';
export const GET_REPORT = 'GET_REPORT';
export const EXAMINATION_ORDER_LIST = 'EXAMINATION_ORDER_LIST';
export const GET_HOSPITAL_LEVELS = 'GET_HOSPITAL_LEVELS';
export const CATEGORIES_LIST = 'CATEGORIES_LIST';
export const POST_LIST = 'POST_LIST';
export const BANNER_LIST = 'BANNER_LIST';
export const EXAMINATION_ORDER_DETAIL_LIST = 'EXAMINATION_ORDER_DETAIL_LIST';
export const CONFIG_INTEGRAL_LIST = 'CONFIG_INTEGRAL_LIST';
export const DIFF_ROUTES = 'DIFF_ROUTES';
export const GET_ROUTES = 'GET_ROUTES';
export const GET_NAV_MENUS = 'GET_NAV_MENUS';

export const GET_ADMINS = 'GET_ADMINS';
export const GET_DEPTS = 'GET_DEPTS';

